using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

[RequireComponent(typeof(Image))]
public class MonsesSimpleImageBehaviour : MonoBehaviour
{
    private Image imageObj;
    public SimpleFloatData dataObj;
    private void Start()
    {
        imageObj = GetComponent<Image>();
    }

    public void UpdateWithFloatData()
    {
        imageObj.fillAmount = dataObj.value;
        if (dataObj.value <= 0f)
        {
            Debug.Log("PlayerIsDead");
            SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
        }
    }

    public void Update()
    {

        if (dataObj.value <= 0f)
        {
            Debug.Log("PlayerIsDead");
            SceneManager.LoadScene(3);

        }

    }

}